name: fl_mlkit_text_recognize
description: Google mlkit text recognize plugin, supports Android and IOS.
version: 0.0.3
repository: https://github.com/Wayaer/fl_mlkit_text_recognize.git

environment:
  sdk: '>=2.12.1 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  fl_camera: ^1.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: fl.mlkit.text.recognize
        pluginClass: FlMlKitTextRecognizePlugin
      ios:
        pluginClass: FlMlkitTextRecognizePlugin
